# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de79401f7c2e4e1a8942e77ab773cfdba7e3e090fb49d1641667b5ee1a4ae4cb3cc7caf326a0cec56c8558eb2e77ce8fae005f9beeca70c1dd632633d5daa6be

test:
  secret_key_base: e6bfdad59a7c14927376f22e02035b43abe1c004c19b60c4b058dc953e49a43b064a9517d83b3c420130fc34290cbe142a07046cc47a22e2319759f2ac84845a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
